# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    pwd
    ls 
  displayName: 'Show current contents'

- script: mkdir cpp/parquet_release
  displayName: 'Create the compilation output folder parquet_release under cpp folder'  

# CMake
- task: CMake@1
  inputs:
    workingDirectory: 'cpp/parquet_release'
    cmakeArgs: -DARROW_PARQUET=ON -DARROW_OPTIONAL_INSTALL=ON -DPARQUET_BUILD_EXAMPLES=ON -DARROW_BUILD_EXAMPLES=ON -DPARQUET_REQUIRE_ENCRYPTION=ON -DARROW_WITH_SNAPPY=ON ..

- script: |
    cd cpp/parquet_release
    make
  displayName: 'Make executables'

- script: |
    cd release
    ls
  displayName: 'Show output folder content'